# Generated by Django 4.2.4 on 2023-08-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('pendente', 'pendente'), ('em andamento', 'em andamento'), ('concluido', 'concluido')], max_length=12),
        ),
    ]
